aurora_token: "5c7bdf499e44b1d4551d19296e8511a43d5cd0a582d232a8073a743982adf5c3"
country_code_list:
  - pol
  - ita
  - deu
  - gbr
  - esp
  - irx
  - fra
  - prt
  - ita_cal
  - ita_cnor
  - ita_csud
  - ita_nor
  - ita_sar
  - ita_sic
  - ita_sud